baseurl = "https://slimfit.khanhicetea.com/"
languageCode = "en-us"
title = "SlimFit Documenation"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
publishdir = "docs"
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "khanhicetea"
	description = "Good enough RESTful API framework built on top Slim 3"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/khanhicetea/slimfit"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "light-green"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "khanhicetea"
	github  = "khanhicetea"


[[menu.main]]
	name   = "SlimFit"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Concepts"
	url    = "concepts/"
	weight = 20

[[menu.main]]
	name   = "HTTP Stack"
	url    = "http-stack/"
	weight = 30

[[menu.main]]
	name   = "Routing - Controller"
	url    = "routing/"
	weight = 40

[[menu.main]]
	name   = "Service Providers"
	url    = "service-provider/"
	weight = 50

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 60


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
